version: 0.1

local:
  local_start_api:
    parameters:
      stack_name: grapple-local-backend
      resolve_s3: true
      capabilities: CAPABILITY_IAM
      parameter_overrides:
        - Environment=local
        - ApiUrl=http://localhost:3000
        - SendGridAPIKey=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
        - CognitoClientID=40s9oop5e9srair8mljupn000j
        - CognitoClientSecret=1fifmgpshit01l5eqppj95o1kjt2v16n32kaunve5ntv2n938ei9
        - DynamoDBEndpoint=http://docker.for.mac.host.internal:8000
        - MongoEndpoint=mongodb://mongodb:27017

test:
  deploy:
    parameters:
      stack_name: grapple-test-backend
      resolve_s3: true
      capabilities: CAPABILITY_NAMED_IAM
      parameter_overrides:
        - Environment=test
        # Warning: we need to change this value if we ever delete and re-create the AWS API Gateway for this environment.
        - ApiUrl=https://kbpyc2vnyh.execute-api.us-west-1.amazonaws.com/Prod
        - SendGridAPIKey=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
        - CognitoClientID=40s9oop5e9srair8mljupn000j
        - CognitoClientSecret=1fifmgpshit01l5eqppj95o1kjt2v16n32kaunve5ntv2n938ei9
        - MongoEndpoint=mongodb+srv://admin:Grapple2024*@grapple-free.pi6vryz.mongodb.net/?retryWrites=true&w=majority&appName=grapple-free
        
prod:
  deploy:
    parameters:
      stack_name: grapple-prod-backend
      resolve_s3: true
      capabilities: CAPABILITY_IAM
      parameter_overrides:
        - Environment=prod

        # Warning: we need to change this value if we ever delete and re-create the AWS API Gateway for this environment.
        - ApiUrl=https://kbpyc2vnyh.execute-api.us-west-1.amazonaws.com/Prod

        - SendGridAPIKey=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
        - CognitoClientID=40s9oop5e9srair8mljupn000j
        - CognitoClientSecret=1fifmgpshit01l5eqppj95o1kjt2v16n32kaunve5ntv2n938ei9
