AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Grapple Backend Service
Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 200
    Runtime: provided.al2

Parameters:
    # all parameters are overriden by samconfig.toml during 'make deploy' recipe.
    Environment:
      Description: "The environment to deploy to, either test or prod is currently supported."
      Type: 'String'
      Default: 'local'
    # all parameters are overriden by samconfig.toml during 'make deploy' recipe.
    ApiUrl:
      Description: "The base api url for grapple, must be hard-coded in samconfig.yml!"
      Type: 'String'
      Default: ''
    MongoEndpoint:
      Description: "The endpoint for mongodb"
      Type: 'String'
      Default: "mongodb://mongodb:27017"
    SendGridAPIKey:
      Description: "The send grid API Key"
      Type: 'String'
      Default: "<sendgrid-api-key>"
    CognitoClientID:
      Description: "The endpoint for dynamodb"
      Type: 'String'
      Default: ""
    UserPoolARN:
      Description: "full ARN of Cognito user pool"
      Type: 'String'
      Default: ""
    CognitoClientSecret:
      Description: "The cognito client secret"
      Type: 'String'
      Default: ""
    CognitoUserPoolID:
      Description: "ID of Cognito User Pool"
      Type: 'String'
      Default: "us-west-1_HT5oR6AwO"
    StripeAPIKey:
      Description: "The Stripe API secret key"
      Type: 'String'
      Default: "sk_test_51QOsVjQ4nix99ZIYPPH7ONKCvpDEO6ui8DZpC3U2ANGEZ1anvWpS2IB0FUhIhNTWehxwHGWmsb7c56Cje3X0TfuV00JjMl2jFL"
    MapBoxAPIKey:
      Description: "The Mapbox API secret key"
      Type: 'String'
      Default: ""    
    JoinGymUrl:
      Description: "The URL to redirect to after joining a gym"
      Type: 'String'
      Default: "http://localhost:3000/auth"
    StripeSecretKey:
      Description: "The Stripe API secret key"
      Type: 'String'
      Default: ""
    StripeWebhookSecret:
      Description: "The Stripe webhook secret"
      Type: 'String'
      Default: ""
    

Resources:
  Gateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'*'"
              Access-Control-Allow-Methods: "'POST, GET, DELETE, PUT, HEAD, OPTIONS'"
        DEFAULT_5XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'*'"
              Access-Control-Allow-Methods: "'POST, GET, DELETE, PUT, HEAD, OPTIONS'"
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'POST, GET, DELETE, PUT, HEAD, OPTIONS'"
        AllowHeaders: "'*'"
      Auth:
        AddDefaultAuthorizerToCorsPreflight: false

  CreateProfileOnSignupLambda:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: !Sub grapple-${Environment}-CreateProfileOnSignup
      CodeUri: ./cmd/post-signup-lambda
      Handler: post-signup
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 1024
      Timeout: 30
      Environment:
        Variables:
          MONGO_ENDPOINT: !Ref MongoEndpoint
      Tracing: Active

  StripeWebhooksLambda:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: !Sub grapple-${Environment}-StripeWebhooksLambda
      CodeUri: ./cmd/stripe-webhooks
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 1024
      Timeout: 30
      Environment:
        Variables:
          MONGO_ENDPOINT: !Ref MongoEndpoint
          STRIPE_SECRET_KEY: !Ref StripeSecretKey
          STRIPE_WEBHOOK_SECRET: !Ref StripeWebhookSecret
      Tracing: Active
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /webhooks/stripe
            Method: POST
      Policies:
        - AWSLambdaBasicExecutionRole

  GrappleLambda:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: !Sub grapple-backend-${Environment}
      CodeUri: ./cmd/backend
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 1024
      Timeout: 30
      Environment:
        Variables:
          API_URL: !Ref ApiUrl
          MONGO_ENDPOINT: !Ref MongoEndpoint
          PUBLIC_USER_ASSETS_BUCKET_NAME: !Sub grapple-${Environment}-public-user-assets
          GYM_VIDEOS_BUCKET_NAME: !Sub grapple-${Environment}-gym-videos
          SENDGRID_API_KEY: !Ref SendGridAPIKey
          COGNITO_USER_POOL_ID: !Ref CognitoUserPoolID
          COGNITO_CLIENT_ID: !Ref CognitoClientID
          COGNITO_CLIENT_SECRET: !Ref CognitoClientSecret
          STRIPE_API_KEY: !Ref StripeAPIKey
          MAPBOX_API_KEY: !Ref MapBoxAPIKey
          JOIN_GYM_URL: !Ref JoinGymUrl

      Tracing: Active
      Role: !GetAtt FunctionRole.Arn
      Events:
        ##### V2 Events
        # Gyms
        GetGym:
          Type: Api
          Properties:
            Path: /gyms/{id}
            Method: GET
            RestApiId: !Ref Gateway


        GetGymStats:
          Type: Api
          Properties:
            Path: /gyms/{id}/stats
            Method: GET
            RestApiId: !Ref Gateway


        GetGyms:
          Type: Api
          Properties:
            Path: /gyms
            Method: GET
            RestApiId: !Ref Gateway


        CreateGym:
          Type: Api
          Properties:
            Path: /gyms
            Method: POST
            RestApiId: !Ref Gateway

        UpdateGym:
          Type: Api
          Properties:
            Path: /gyms/{id}
            Method: PUT
            RestApiId: !Ref Gateway

        PresignGymObject:
          Type: Api
          Properties:
            Path: /gyms/{id}/presign
            Method: PUT
            RestApiId: !Ref Gateway

        AssignGymRole:
          Type: Api
          Properties:
            Path: /gyms/{id}/assign-role
            Method: PUT
            RestApiId: !Ref Gateway

        DeleteGym:
          Type: Api
          Properties:
            Path: /gyms/{id}
            Method: DELETE
            RestApiId: !Ref Gateway

        # Gym Requests
        GetGymRequest:
          Type: Api
          Properties:
            Path: /gym-requests/{id}
            Method: GET
            RestApiId: !Ref Gateway

        GetGymRequests:
          Type: Api
          Properties:
            Path: /gym-requests
            Method: GET
            RestApiId: !Ref Gateway

        EmailBlastUsers:
          Type: Api
          Properties:
            Path: /gym-requests/{id}
            Method: POST
            RestApiId: !Ref Gateway

        CreateGymRequest:
          Type: Api
          Properties:
            Path: /gym-requests
            Method: POST
            RestApiId: !Ref Gateway

        UpdateGymRequest:
          Type: Api
          Properties:
            Path: /gym-requests/{id}
            Method: PUT
            RestApiId: !Ref Gateway

        DeleteGymRequest:
          Type: Api
          Properties:
            Path: /gym-requests/{id}
            Method: DELETE
            RestApiId: !Ref Gateway
            
        AddToEmailList:
          Type: Api
          Properties:
            Path: /emails
            Method: POST
            RestApiId: !Ref Gateway

        SendDemoEmail:
          Type: Api
          Properties:
            Path: /emails/demo
            Method: POST
            RestApiId: !Ref Gateway

        # Announcements
        GetAnnouncement:
          Type: Api
          Properties:
            Path: /announcements/{id}
            Method: GET
            RestApiId: !Ref Gateway

        GetAnnouncements:
          Type: Api
          Properties:
            Path: /announcements
            Method: GET
            RestApiId: !Ref Gateway

        CreateAnnouncement:
          Type: Api
          Properties:
            Path: /announcements
            Method: POST
            RestApiId: !Ref Gateway

        UpdateAnnouncement:
          Type: Api
          Properties:
            Path: /announcements/{id}
            Method: PUT
            RestApiId: !Ref Gateway

        DeleteAnnouncement:
          Type: Api
          Properties:
            Path: /announcements/{id}
            Method: DELETE
            RestApiId: !Ref Gateway

        # Gym Series
        GetSeriesByID:
          Type: Api
          Properties:
            Path: /gym-series/{id}
            Method: GET
            RestApiId: !Ref Gateway

        GetSeries:
          Type: Api
          Properties:
            Path: /gym-series
            Method: GET
            RestApiId: !Ref Gateway

        CreateSeries:
          Type: Api
          Properties:
            Path: /gym-series
            Method: POST
            RestApiId: !Ref Gateway

        PresignSeriesObject:
          Type: Api
          Properties:
            Path: /gym-series/{id}/presign
            Method: PUT
            RestApiId: !Ref Gateway

        UpsertVideo:
          Type: Api
          Properties:
            Path: /gym-series/{id}/videos
            Method: PUT
            RestApiId: !Ref Gateway

        UpdateSeries:
          Type: Api
          Properties:
            Path: /gym-series/{id}
            Method: PUT
            RestApiId: !Ref Gateway

        DeleteSeries:
          Type: Api
          Properties:
            Path: /gym-series/{id}
            Method: DELETE
            RestApiId: !Ref Gateway

        DeleteSeriesVideo:
          Type: Api
          Properties:
            Path: /gym-series/{id}/videos/{video_id}
            Method: DELETE
            RestApiId: !Ref Gateway

        # Techniques
        GetTechniques:
          Type: Api
          Properties:
            Path: /techniques/{id}
            Method: GET
            RestApiId: !Ref Gateway


        GetTechnique:
          Type: Api
          Properties:
            Path: /techniques
            Method: GET
            RestApiId: !Ref Gateway


        CreateTechnique:
          Type: Api
          Properties:
            Path: /techniques
            Method: POST
            RestApiId: !Ref Gateway

        UpdateTechnique:
          Type: Api
          Properties:
            Path: /techniques/{id}
            Method: PUT
            RestApiId: !Ref Gateway

        DeleteTechnique:
          Type: Api
          Properties:
            Path: /techniques/{id}
            Method: DELETE
            RestApiId: !Ref Gateway

        # Profiles
        GetProfiles:
          Type: Api
          Properties:
            Path: /profiles
            Method: GET
            RestApiId: !Ref Gateway

        GeneratePresignedAvatarUploadURL:
          Type: Api
          Properties:
            Path: /profiles/avatar
            Method: PUT
            RestApiId: !Ref Gateway

        UpsertUserProfile:
          Type: Api
          Properties:
            Path: /profiles
            Method: PUT
            RestApiId: !Ref Gateway

        DeleteProfile:
          Type: Api
          Properties:
            Path: /profiles/{id}
            Method: DELETE
            RestApiId: !Ref Gateway

        GetSubscriptions:
          Type: Api
          Properties:
            Path: /subscriptions
            Method: GET
            RestApiId: !Ref Gateway

        # S3 multi-part uploads
        StartUpload:
          Type: Api
          Properties:
            Path: /s3/start-upload
            Method: GET
            RestApiId: !Ref Gateway

        CompleteUpload:
          Type: Api
          Properties:
            Path: /s3/complete-upload
            Method: POST
            RestApiId: !Ref Gateway

        # Miscellaneous endpoints
        Search:
          Type: Api
          Properties:
            Path: /search
            Method: GET
            RestApiId: !Ref Gateway

        MapboxGeocodeForward:
          Type: Api
          Properties:
            Path: /mapbox
            Method: GET
            RestApiId: !Ref Gateway

  FunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "grapple-${Environment}-backend-execution-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - s3:*
                Resource:
                  - !Sub arn:aws:s3:::grapple-${Environment}-gym-videos
                  - !Sub arn:aws:s3:::grapple-${Environment}-gym-videos/*
                  - !Sub arn:aws:s3:::grapple-${Environment}-public-user-assets
                  - !Sub arn:aws:s3:::grapple-${Environment}-public-user-assets/*
        - PolicyName: CognitoIdpAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cognito-idp:AdminListGroupsForUser
                  - cognito-idp:AdminDeleteUser
                  - cognito-idp:AdminAddUserToGroup
                Resource: '*'
        - PolicyName: CognitoUserPools
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cognito-idp:*
                Resource: '*'
Outputs:
  API:
    Description: "API Gateway endpoint URL for the Lambda function"
    Value: !Sub "https://${Gateway}.execute-api.${AWS::Region}.amazonaws.com/"
  GrappleLambdaARN:
    Description: "Content Service Lambda Function ARN"
    Value: !GetAtt GrappleLambda.Arn
  GrappleFunctionIAMRole:
    Description: "Implicit IAM Role created for Grapple Backend Lambda function"
    Value: !GetAtt FunctionRole.Arn