# https://docs.aws.amazon.com/AWSCloudFormation/latest/ContentGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Grapple Backend Service
# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/ContentGuide/transform-section-structure.html
Transform:
  - AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/ContentGuide/resources-section-structure.html

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 200
    Runtime: go1.x
    Environment:

Parameters:
    GymsTableName:
        Description: 'Name of the Gyms table'
        Type: 'String'
        Default: 'grapple-gyms' 
    GymRequestsTableName:
        Description: 'Name of the Gym Requests table'
        Type: 'String'
        Default: 'grapple-gym-requests' 
    GymAnnouncementsTableName:
        Description: 'Name of the Gym Announcements table'
        Type: 'String'
        Default: 'grapple-gym-announcements'
    GymVideosTableName:
        Description: 'Name of the Gym Videos table'
        Type: 'String'
        Default: 'grapple-gym-videos'
Resources:
  Gateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              Access-Control-Allow-Methods: "'GET,OPTIONS,POST'"
        DEFAULT_5XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              Access-Control-Allow-Methods: "'GET,OPTIONS,POST'"
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'POST, GET, DELETE, PUT, HEAD, OPTIONS'"
        AllowHeaders: "'*'"
      Auth:
        AddDefaultAuthorizerToCorsPreflight: false
        DefaultAuthorizer: MyCognitoAuth # OPTIONAL
        Authorizers:
          MyCognitoAuth:
            UserPoolArn: arn:aws:cognito-idp:us-west-1:381491926210:userpool/us-west-1_HT5oR6AwO # Can also accept an array
            Identity: # OPTIONAL
              Header: Authorization # OPTIONAL; Default: 'Authorization'

  GymsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref GymsTableName
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: creator
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: "CreatorIndex"
          KeySchema: 
          - AttributeName: creator
            KeyType: HASH
          Projection: 
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

  GymRequestsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref GymRequestsTableName
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: gym_id
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
        - AttributeName: dummy
          AttributeType: S
        - AttributeName: requestor_id
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: "GymIndex"
          KeySchema: 
          - AttributeName: gym_id
            KeyType: HASH
          Projection: 
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: "CreatedAtIndex"
          KeySchema:
          - AttributeName: dummy
            KeyType: HASH
          - AttributeName: created_at
            KeyType: RANGE
          Projection: 
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: "RequestorIndex"
          KeySchema:
          - AttributeName: requestor_id
            KeyType: HASH
          Projection: 
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

  GymAnnouncementsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref GymAnnouncementsTableName
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: dummy
          AttributeType: S
        - AttributeName: updated_at
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: "LastUpdatedIndex"
          KeySchema: 
          - AttributeName: dummy
            KeyType: HASH
          - AttributeName: updated_at
            KeyType: RANGE
          Projection: 
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

  GymVideosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref GymVideosTableName
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: gym_id
          AttributeType: S
        - AttributeName: dummy
          AttributeType: S
        - AttributeName: updated_at
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: "GymIndex"
          KeySchema: 
          - AttributeName: gym_id
            KeyType: HASH
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: "LastUpdatedIndex"
          KeySchema:
          - AttributeName: dummy
            KeyType: HASH
          - AttributeName: updated_at
            KeyType: RANGE
          Projection: 
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: grapple-backend
      CodeUri: ./cmd/backend
      Handler: main
      MemorySize: 512
      Timeout: 30
      
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: !Sub "https://dynamodb.${AWS::Region}.amazonaws.com"
          GYMS_TABLE_NAME: !Ref GymsTableName
          GYM_REQUESTS_TABLE_NAME: !Ref GymRequestsTableName
          GYM_ANNOUNCEMENTS_TABLE_NAME: !Ref GymAnnouncementsTableName
          GYM_VIDEOS_TABLE_NAME: !Ref GymVideosTableName
      Tracing: Active
      Policies:
        - S3FullAccessPolicy:
            BucketName: grapple-gym-videos # bucket name without arn
        - DynamoDBCrudPolicy:
            TableName: !Ref GymsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref GymRequestsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref GymAnnouncementsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref GymVideosTable
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:AdminAddUserToGroup
              Resource: '*'
      Events:
        # Gyms
        GetGym:
          Type: Api
          Properties:
            Path: /gyms/{id}
            Method: GET
            RestApiId: !Ref Gateway
            
        GetGyms:
          Type: Api
          Properties:
            Path: /gyms
            Method: GET
            RestApiId: !Ref Gateway
            Auth:
              Authorizer: NONE # Turn off Authorization for this event

        CreateGym:
          Type: Api
          Properties:
            Path: /gyms
            Method: POST
            RestApiId: !Ref Gateway

        UpdateGym:
          Type: Api
          Properties:
            Path: /gyms/{id}
            Method: PUT
            RestApiId: !Ref Gateway

        DeleteGym:
          Type: Api
          Properties:
            Path: /gyms/{id}
            Method: DELETE
            RestApiId: !Ref Gateway

        # Gym Requests
        GetGymRequest:
          Type: Api
          Properties:
            Path: /gym-requests/{id}
            Method: GET
            RestApiId: !Ref Gateway
            
        GetGymRequests:
          Type: Api
          Properties:
            Path: /gym-requests
            Method: GET
            RestApiId: !Ref Gateway

        CreateGymRequest:
          Type: Api
          Properties:
            Path: /gym-requests
            Method: POST
            RestApiId: !Ref Gateway

        UpdateGymRequest:
          Type: Api
          Properties:
            Path: /gym-requests/{id}
            Method: PUT
            RestApiId: !Ref Gateway

        DeleteGymRequest:
          Type: Api
          Properties:
            Path: /gym-requests/{id}
            Method: DELETE
            RestApiId: !Ref Gateway

        # Gym Announcements
        GetGymAnnouncement:
          Type: Api
          Properties:
            Path: /gym-announcements/{id}
            Method: GET
            RestApiId: !Ref Gateway
            
        GetGymAnnouncements:
          Type: Api
          Properties:
            Path: /gym-announcements
            Method: GET
            RestApiId: !Ref Gateway

        CreateGymAnnouncement:
          Type: Api
          Properties:
            Path: /gym-announcements
            Method: POST
            RestApiId: !Ref Gateway

        UpdateGymAnnouncement:
          Type: Api
          Properties:
            Path: /gym-announcements/{id}
            Method: PUT
            RestApiId: !Ref Gateway

        DeleteGymAnnouncement:
          Type: Api
          Properties:
            Path: /gym-announcements/{id}
            Method: DELETE
            RestApiId: !Ref Gateway

        # Gym Videos
        GetGymVideo:
          Type: Api
          Properties:
            Path: /gym-videos/{id}
            Method: GET
            RestApiId: !Ref Gateway
            
        GetGymVideos:
          Type: Api
          Properties:
            Path: /gym-videos
            Method: GET
            RestApiId: !Ref Gateway

        CreateGymVideo:
          Type: Api
          Properties:
            Path: /gym-videos
            Method: POST
            RestApiId: !Ref Gateway

        UpdateGymVideo:
          Type: Api
          Properties:
            Path: /gym-videos/{id}
            Method: PUT
            RestApiId: !Ref Gateway

        DeleteGymVideo:
          Type: Api
          Properties:
            Path: /gym-videos/{id}
            Method: DELETE
            RestApiId: !Ref Gateway


        # Get Pre-signed S3 Upload URL
        GetS3SignedURL:
          Type: Api
          Properties:
            Path: /s3-presign-url
            Method: GET
            RestApiId: !Ref Gateway

Outputs:
  API:
    Description: "API Gateway endpoint URL for the Lambda function"
    Value: !Sub "https://${Gateway}.execute-api.${AWS::Region}.amazonaws.com/"
  FunctionARN:
    Description: "Content Service Function ARN"
    Value: !GetAtt Function.Arn
  FunctionIAMRole:
    Description: "Implicit IAM Role created for Grapple Backend Lambda function"
    Value: !GetAtt FunctionRole.Arn